name = "understandingtrauma"
pages_build_output_dir = "."
compatibility_date = "2026-06-24"
[[d1_databases]]
binding = "DB"
database_name = "understandingtrauma-db"
database_id = "bafbc3ed-7fd3-4f53-aa10-d7fff1591e78"
