CREATE TABLE IF NOT EXISTS faith_messages (
id INTEGER PRIMARY KEY AUTOINCREMENT,
message TEXT NOT NULL,
reference TEXT,
kind TEXT NOT NULL DEFAULT 'encouragement' CHECK(kind IN ('verse','encouragement','prayer','saying')),
verse_text TEXT,
verse_reference TEXT,
status TEXT NOT NULL DEFAULT 'approved' CHECK(status IN ('approved','draft')),
created_at TEXT NOT NULL DEFAULT (datetime('now')),
UNIQUE(message, reference)
);
CREATE INDEX IF NOT EXISTS idx_faith_messages_status_kind ON faith_messages(status, kind);
ALTER TABLE faith_messages ADD COLUMN verse_text TEXT;
ALTER TABLE faith_messages ADD COLUMN verse_reference TEXT;
-- If the ALTER TABLE statements above say duplicate column name, that is okay. Continue with the INSERT statements below.
INSERT OR IGNORE INTO faith_messages (message, reference, kind, verse_text, verse_reference, status) VALUES
('God is our refuge and strength, a very present help in trouble.', 'Psalm 46:1 KJV', 'verse', 'God is our refuge and strength, a very present help in trouble.', 'Psalm 46:1 KJV', 'approved'),
('Fear thou not; for I am with thee: be not dismayed; for I am thy God.', 'Isaiah 41:10 KJV', 'verse', 'Fear thou not; for I am with thee: be not dismayed; for I am thy God.', 'Isaiah 41:10 KJV', 'approved'),
('Come unto me, all ye that labour and are heavy laden, and I will give you rest.', 'Matthew 11:28 KJV', 'verse', 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.', 'Matthew 11:28 KJV', 'approved'),
('Peace I leave with you, my peace I give unto you.', 'John 14:27 KJV', 'verse', 'Peace I leave with you, my peace I give unto you.', 'John 14:27 KJV', 'approved'),
('The LORD is nigh unto them that are of a broken heart.', 'Psalm 34:18 KJV', 'verse', 'The LORD is nigh unto them that are of a broken heart.', 'Psalm 34:18 KJV', 'approved'),
('For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.', '2 Timothy 1:7 KJV', 'verse', 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.', '2 Timothy 1:7 KJV', 'approved'),
('Be strong and of a good courage; be not afraid, neither be thou dismayed.', 'Joshua 1:9 KJV', 'verse', 'Be strong and of a good courage; be not afraid, neither be thou dismayed.', 'Joshua 1:9 KJV', 'approved'),
('The LORD is my shepherd; I shall not want.', 'Psalm 23:1 KJV', 'verse', 'The LORD is my shepherd; I shall not want.', 'Psalm 23:1 KJV', 'approved'),
('Cast thy burden upon the LORD, and he shall sustain thee.', 'Psalm 55:22 KJV', 'verse', 'Cast thy burden upon the LORD, and he shall sustain thee.', 'Psalm 55:22 KJV', 'approved'),
('He healeth the broken in heart, and bindeth up their wounds.', 'Psalm 147:3 KJV', 'verse', 'He healeth the broken in heart, and bindeth up their wounds.', 'Psalm 147:3 KJV', 'approved'),
('Thou wilt keep him in perfect peace, whose mind is stayed on thee.', 'Isaiah 26:3 KJV', 'verse', 'Thou wilt keep him in perfect peace, whose mind is stayed on thee.', 'Isaiah 26:3 KJV', 'approved'),
('They that wait upon the LORD shall renew their strength.', 'Isaiah 40:31 KJV', 'verse', 'They that wait upon the LORD shall renew their strength.', 'Isaiah 40:31 KJV', 'approved'),
('When thou passest through the waters, I will be with thee.', 'Isaiah 43:2 KJV', 'verse', 'When thou passest through the waters, I will be with thee.', 'Isaiah 43:2 KJV', 'approved'),
('They are new every morning: great is thy faithfulness.', 'Lamentations 3:23 KJV', 'verse', 'They are new every morning: great is thy faithfulness.', 'Lamentations 3:23 KJV', 'approved'),
('Blessed are they that mourn: for they shall be comforted.', 'Matthew 5:4 KJV', 'verse', 'Blessed are they that mourn: for they shall be comforted.', 'Matthew 5:4 KJV', 'approved'),
('Be not afraid, only believe.', 'Mark 5:36 KJV', 'verse', 'Be not afraid, only believe.', 'Mark 5:36 KJV', 'approved'),
('If God be for us, who can be against us?', 'Romans 8:31 KJV', 'verse', 'If God be for us, who can be against us?', 'Romans 8:31 KJV', 'approved'),
('My grace is sufficient for thee: for my strength is made perfect in weakness.', '2 Corinthians 12:9 KJV', 'verse', 'My grace is sufficient for thee: for my strength is made perfect in weakness.', '2 Corinthians 12:9 KJV', 'approved'),
('I can do all things through Christ which strengtheneth me.', 'Philippians 4:13 KJV', 'verse', 'I can do all things through Christ which strengtheneth me.', 'Philippians 4:13 KJV', 'approved'),
('I will never leave thee, nor forsake thee.', 'Hebrews 13:5 KJV', 'verse', 'I will never leave thee, nor forsake thee.', 'Hebrews 13:5 KJV', 'approved'),
('Casting all your care upon him; for he careth for you.', '1 Peter 5:7 KJV', 'verse', 'Casting all your care upon him; for he careth for you.', '1 Peter 5:7 KJV', 'approved'),
('There is no fear in love; but perfect love casteth out fear.', '1 John 4:18 KJV', 'verse', 'There is no fear in love; but perfect love casteth out fear.', '1 John 4:18 KJV', 'approved'),
('The LORD will give strength unto his people; the LORD will bless his people with peace.', 'Psalm 29:11 KJV', 'verse', 'The LORD will give strength unto his people; the LORD will bless his people with peace.', 'Psalm 29:11 KJV', 'approved'),
('Weeping may endure for a night, but joy cometh in the morning.', 'Psalm 30:5 KJV', 'verse', 'Weeping may endure for a night, but joy cometh in the morning.', 'Psalm 30:5 KJV', 'approved'),
('Be of good courage, and he shall strengthen your heart.', 'Psalm 31:24 KJV', 'verse', 'Be of good courage, and he shall strengthen your heart.', 'Psalm 31:24 KJV', 'approved'),
('In the multitude of my thoughts within me thy comforts delight my soul.', 'Psalm 94:19 KJV', 'verse', 'In the multitude of my thoughts within me thy comforts delight my soul.', 'Psalm 94:19 KJV', 'approved'),
('The LORD is on my side; I will not fear.', 'Psalm 118:6 KJV', 'verse', 'The LORD is on my side; I will not fear.', 'Psalm 118:6 KJV', 'approved'),
('Trust in the LORD with all thine heart; and lean not unto thine own understanding.', 'Proverbs 3:5 KJV', 'verse', 'Trust in the LORD with all thine heart; and lean not unto thine own understanding.', 'Proverbs 3:5 KJV', 'approved'),
('The name of the LORD is a strong tower: the righteous runneth into it, and is safe.', 'Proverbs 18:10 KJV', 'verse', 'The name of the LORD is a strong tower: the righteous runneth into it, and is safe.', 'Proverbs 18:10 KJV', 'approved'),
('For we walk by faith, not by sight.', '2 Corinthians 5:7 KJV', 'verse', 'For we walk by faith, not by sight.', '2 Corinthians 5:7 KJV', 'approved'),
('Pray without ceasing.', '1 Thessalonians 5:17 KJV', 'verse', 'Pray without ceasing.', '1 Thessalonians 5:17 KJV', 'approved'),
('Jesus Christ the same yesterday, and to day, and for ever.', 'Hebrews 13:8 KJV', 'verse', 'Jesus Christ the same yesterday, and to day, and for ever.', 'Hebrews 13:8 KJV', 'approved'),
('God can meet you in the middle of the breath you are barely able to take.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('You do not have to be strong enough for the whole road. Ask God for grace for the next step.', NULL, 'encouragement', 'God is our refuge and strength, a very present help in trouble.', 'Psalm 46:1 KJV', 'approved'),
('The Lord is not disappointed by your tiredness. He is gentle with the weary.', NULL, 'encouragement', 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.', 'Matthew 11:28 KJV', 'approved'),
('Healing can be slow and still be sacred.', NULL, 'encouragement', 'He healeth the broken in heart, and bindeth up their wounds.', 'Psalm 147:3 KJV', 'approved'),
('Grace is not only for your polished places. Grace meets you in the places you hide.', NULL, 'encouragement', 'My grace is sufficient for thee: for my strength is made perfect in weakness.', '2 Corinthians 12:9 KJV', 'approved'),
('God is not asking you to pretend this does not hurt.', NULL, 'encouragement', 'The LORD is nigh unto them that are of a broken heart.', 'Psalm 34:18 KJV', 'approved'),
('You can bring the anxious thought to Jesus before you know how to fix it.', NULL, 'encouragement', 'Casting all your care upon him; for he careth for you.', '1 Peter 5:7 KJV', 'approved'),
('Your tears are not wasted in the presence of God.', NULL, 'encouragement', 'And God shall wipe away all tears from their eyes.', 'Revelation 21:4 KJV', 'approved'),
('The same God who holds tomorrow can hold this minute.', NULL, 'encouragement', 'Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself.', 'Matthew 6:34 KJV', 'approved'),
('You are not too broken for the love of Christ.', NULL, 'encouragement', 'The LORD is nigh unto them that are of a broken heart.', 'Psalm 34:18 KJV', 'approved'),
('God can restore peace without rushing your process.', NULL, 'encouragement', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.', 'John 14:27 KJV', 'approved'),
('A small prayer still reaches heaven.', NULL, 'prayer', 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.', 'Hebrews 4:16 KJV', 'approved'),
('You can whisper, ''Lord, help me,'' and that is enough for this moment.', NULL, 'prayer', 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.', 'Hebrews 4:16 KJV', 'approved');
INSERT OR IGNORE INTO faith_messages (message, reference, kind, verse_text, verse_reference, status) VALUES
('God sees the part of you that kept going quietly.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('The valley is real, but so is the Shepherd.', NULL, 'saying', 'Yea, though I walk through the valley of the shadow of death, I will fear no evil.', 'Psalm 23:4 KJV', 'approved'),
('You are held by a grace that does not let go when you feel weak.', NULL, 'encouragement', 'My grace is sufficient for thee: for my strength is made perfect in weakness.', '2 Corinthians 12:9 KJV', 'approved'),
('God''s nearness is not canceled by your fear.', NULL, 'encouragement', 'Fear thou not; for I am with thee: be not dismayed; for I am thy God.', 'Isaiah 41:10 KJV', 'approved'),
('You can rest without earning it. Rest was God''s idea first.', NULL, 'saying', 'Return unto thy rest, O my soul; for the LORD hath dealt bountifully with thee.', 'Psalm 116:7 KJV', 'approved'),
('Jesus is not offended by your need for comfort.', NULL, 'encouragement', 'Blessed are they that mourn: for they shall be comforted.', 'Matthew 5:4 KJV', 'approved'),
('The Lord can make room for peace even in a crowded heart.', NULL, 'encouragement', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.', 'John 14:27 KJV', 'approved'),
('God is still writing tenderness into your story.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('There is mercy for the version of you that is still learning how to heal.', NULL, 'encouragement', 'He healeth the broken in heart, and bindeth up their wounds.', 'Psalm 147:3 KJV', 'approved'),
('You do not have to carry shame into a place where Jesus offers grace.', NULL, 'encouragement', 'My grace is sufficient for thee: for my strength is made perfect in weakness.', '2 Corinthians 12:9 KJV', 'approved'),
('Your nervous system may feel unsafe, but your soul can be reminded that God is near.', NULL, 'encouragement', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.', 'John 14:27 KJV', 'approved'),
('Today, let prayer be simple: Lord, stay close.', NULL, 'prayer', 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.', 'Hebrews 4:16 KJV', 'approved'),
('The Lord does not despise small beginnings or small steps.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('God''s love is not fragile. It can hold your questions.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('You can be honest with God about the part that still hurts.', NULL, 'encouragement', 'The LORD is nigh unto them that are of a broken heart.', 'Psalm 34:18 KJV', 'approved'),
('Faith does not mean you never tremble. Sometimes faith is reaching for God while you tremble.', NULL, 'saying', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('God can bring calm to places that have only known survival.', NULL, 'encouragement', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.', 'John 14:27 KJV', 'approved'),
('You are not forgotten in the quiet season.', NULL, 'encouragement', 'I will never leave thee, nor forsake thee.', 'Hebrews 13:5 KJV', 'approved'),
('The Holy Spirit can comfort what words cannot explain.', NULL, 'encouragement', 'Blessed are they that mourn: for they shall be comforted.', 'Matthew 5:4 KJV', 'approved'),
('Lord, give me enough peace for this moment and enough courage for the next one.', NULL, 'prayer', 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.', 'Hebrews 4:16 KJV', 'approved'),
('God is not waiting for you to be less human before He loves you.', NULL, 'encouragement', 'Now the God of hope fill you with all joy and peace in believing.', 'Romans 15:13 KJV', 'approved'),
('There is room at the feet of Jesus for your exhaustion.', NULL, 'encouragement', 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.', 'Matthew 11:28 KJV', 'approved'),
('Your weakness is not a locked door to God. It is often where grace enters.', NULL, 'saying', 'My grace is sufficient for thee: for my strength is made perfect in weakness.', '2 Corinthians 12:9 KJV', 'approved'),
('Even when your heart feels scattered, God can gather you gently.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('You can lay down what was never yours to carry.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('The Lord is patient with slow healing.', NULL, 'encouragement', 'He healeth the broken in heart, and bindeth up their wounds.', 'Psalm 147:3 KJV', 'approved'),
('You do not have to perform peace to be loved by the Prince of Peace.', NULL, 'encouragement', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.', 'John 14:27 KJV', 'approved'),
('A hard season does not mean God has turned away.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('God can be trusted with the chapter you would not have chosen.', NULL, 'encouragement', 'Trust in the LORD with all thine heart; and lean not unto thine own understanding.', 'Proverbs 3:5 KJV', 'approved'),
('Let grace speak louder than the accusation in your mind.', NULL, 'saying', 'My grace is sufficient for thee: for my strength is made perfect in weakness.', '2 Corinthians 12:9 KJV', 'approved'),
('You are still seen, still loved, and still held.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('Lord, quiet what is racing and strengthen what is weary.', NULL, 'prayer', 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.', 'Hebrews 4:16 KJV', 'approved'),
('Jesus meets people in storms, not only after storms.', NULL, 'saying', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('Your faith can be small and still be real.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('The Lord can hold both your hope and your heartbreak.', NULL, 'encouragement', 'Now the God of hope fill you with all joy and peace in believing.', 'Romans 15:13 KJV', 'approved'),
('You can stop striving for a moment and receive mercy.', NULL, 'encouragement', 'It is of the LORD''s mercies that we are not consumed, because his compassions fail not.', 'Lamentations 3:22 KJV', 'approved'),
('God does not require perfect words. He receives honest prayers.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('This moment is not bigger than God''s compassion.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('The cross says your pain is not invisible to God.', NULL, 'saying', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('God can redeem what trauma tried to rename.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('You are not beyond repair. The Restorer is gentle.', NULL, 'encouragement', 'He healeth the broken in heart, and bindeth up their wounds.', 'Psalm 147:3 KJV', 'approved'),
('The Lord can make your heart a safer place to live.', NULL, 'encouragement', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.', 'John 14:27 KJV', 'approved'),
('When you cannot find the words, let your breathing become a prayer.', NULL, 'saying', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('God is near in the ordinary, quiet, unimpressive steps of healing.', NULL, 'encouragement', 'He healeth the broken in heart, and bindeth up their wounds.', 'Psalm 147:3 KJV', 'approved'),
('Lord, help me receive the peace I cannot create by myself.', NULL, 'prayer', 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.', 'Hebrews 4:16 KJV', 'approved');
INSERT OR IGNORE INTO faith_messages (message, reference, kind, verse_text, verse_reference, status) VALUES
('Grace is enough for the parts of you that feel unfinished.', NULL, 'encouragement', 'My grace is sufficient for thee: for my strength is made perfect in weakness.', '2 Corinthians 12:9 KJV', 'approved'),
('You can trust God with the timing of your healing.', NULL, 'encouragement', 'He healeth the broken in heart, and bindeth up their wounds.', 'Psalm 147:3 KJV', 'approved'),
('There is no shame in needing God again today.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('God can bring light into rooms you thought would always stay dark.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('You are not alone in the waiting.', NULL, 'encouragement', 'Now the God of hope fill you with all joy and peace in believing.', 'Romans 15:13 KJV', 'approved'),
('The Lord''s gentleness can reach the memory that still aches.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('You can be loved by God before you feel whole.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('Faith is not denial. Faith is bringing the truth to the One who can hold it.', NULL, 'saying', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('God''s mercy is not running out on you.', NULL, 'encouragement', 'It is of the LORD''s mercies that we are not consumed, because his compassions fail not.', 'Lamentations 3:22 KJV', 'approved'),
('You can ask for help and still be faithful.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('The Lord sees the battle nobody else noticed.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('Jesus is not asking you to heal alone.', NULL, 'encouragement', 'He healeth the broken in heart, and bindeth up their wounds.', 'Psalm 147:3 KJV', 'approved'),
('God''s peace can be gentle before it feels strong.', NULL, 'encouragement', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.', 'John 14:27 KJV', 'approved'),
('Lord, teach my body that Your presence is safe.', NULL, 'prayer', 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.', 'Hebrews 4:16 KJV', 'approved'),
('Your story is not over because a chapter was painful.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('The God who restores souls is not intimidated by your wounds.', NULL, 'encouragement', 'He healeth the broken in heart, and bindeth up their wounds.', 'Psalm 147:3 KJV', 'approved'),
('You are allowed to need comfort, prayer, and time.', NULL, 'encouragement', 'Blessed are they that mourn: for they shall be comforted.', 'Matthew 5:4 KJV', 'approved'),
('God is not in a hurry with your healing.', NULL, 'encouragement', 'He healeth the broken in heart, and bindeth up their wounds.', 'Psalm 147:3 KJV', 'approved'),
('The Lord can turn survival into steadiness, one day at a time.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('You can bring God the mess, not just the lesson.', NULL, 'saying', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('Jesus knows how to be gentle with wounded people.', NULL, 'encouragement', 'He healeth the broken in heart, and bindeth up their wounds.', 'Psalm 147:3 KJV', 'approved'),
('A quiet prayer can be an act of courage.', NULL, 'saying', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('God can strengthen you without hardening your heart.', NULL, 'encouragement', 'God is our refuge and strength, a very present help in trouble.', 'Psalm 46:1 KJV', 'approved'),
('Let the love of Christ be louder than the fear that says you are alone.', NULL, 'encouragement', 'Fear thou not; for I am with thee: be not dismayed; for I am thy God.', 'Isaiah 41:10 KJV', 'approved'),
('The Lord can help you feel safe in small pieces.', NULL, 'encouragement', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.', 'John 14:27 KJV', 'approved'),
('You do not have to understand everything to be held by God.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('God''s presence can be peace before your circumstances change.', NULL, 'encouragement', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.', 'John 14:27 KJV', 'approved'),
('Lord, help me take the next right breath.', NULL, 'prayer', 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.', 'Hebrews 4:16 KJV', 'approved'),
('You are not disqualified by the days you struggle.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('Grace covers the places where survival taught you to be afraid.', NULL, 'encouragement', 'Fear thou not; for I am with thee: be not dismayed; for I am thy God.', 'Isaiah 41:10 KJV', 'approved'),
('God can be close even when your feelings are loud.', NULL, 'encouragement', 'Draw nigh to God, and he will draw nigh to you.', 'James 4:8 KJV', 'approved'),
('You can be fragile and still be faithful.', NULL, 'saying', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('The Lord is not ashamed to be near your broken places.', NULL, 'encouragement', 'The LORD is nigh unto them that are of a broken heart.', 'Psalm 34:18 KJV', 'approved'),
('Your healing matters to God.', NULL, 'encouragement', 'He healeth the broken in heart, and bindeth up their wounds.', 'Psalm 147:3 KJV', 'approved'),
('There is mercy for today and hope for tomorrow.', NULL, 'encouragement', 'Now the God of hope fill you with all joy and peace in believing.', 'Romans 15:13 KJV', 'approved'),
('Let Jesus be enough for the step you cannot take alone.', NULL, 'encouragement', 'I will never leave thee, nor forsake thee.', 'Hebrews 13:5 KJV', 'approved'),
('God can carry what your hands cannot hold anymore.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('The Lord is still kind in the middle of the unknown.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('You can rest beneath the care of a faithful Father.', NULL, 'encouragement', 'Casting all your care upon him; for he careth for you.', '1 Peter 5:7 KJV', 'approved'),
('God''s love does not shrink back from hard stories.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('When your heart feels heavy, you can still be held.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('Lord, make a little room in me for peace today.', NULL, 'prayer', 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.', 'Hebrews 4:16 KJV', 'approved'),
('The Shepherd does not abandon sheep in valleys.', NULL, 'saying', 'Yea, though I walk through the valley of the shadow of death, I will fear no evil.', 'Psalm 23:4 KJV', 'approved'),
('God can meet you in the pause before panic takes over.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('Your need is not too much for God''s compassion.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved');
INSERT OR IGNORE INTO faith_messages (message, reference, kind, verse_text, verse_reference, status) VALUES
('The Lord can restore your sense of safety without forcing you to rush.', NULL, 'encouragement', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.', 'John 14:27 KJV', 'approved'),
('Jesus can sit with you in the ache without demanding a performance.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('Your heart is worth tending gently.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('God can make beauty grow in soil that grief watered.', NULL, 'saying', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('You are not alone when the night feels long.', NULL, 'encouragement', 'I will never leave thee, nor forsake thee.', 'Hebrews 13:5 KJV', 'approved'),
('The Lord understands groans that never become sentences.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('You can let prayer be small today.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('Grace does not ask you to pretend you are fine.', NULL, 'saying', 'My grace is sufficient for thee: for my strength is made perfect in weakness.', '2 Corinthians 12:9 KJV', 'approved'),
('God can rebuild trust slowly and tenderly.', NULL, 'encouragement', 'Trust in the LORD with all thine heart; and lean not unto thine own understanding.', 'Proverbs 3:5 KJV', 'approved'),
('You are deeply loved in the middle of your process.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('The Lord can steady what trauma shook.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('God is not distant from your tears.', NULL, 'encouragement', 'And God shall wipe away all tears from their eyes.', 'Revelation 21:4 KJV', 'approved'),
('You can bring the younger, hurting parts of you to Jesus.', NULL, 'encouragement', 'The LORD is nigh unto them that are of a broken heart.', 'Psalm 34:18 KJV', 'approved'),
('Lord, help me feel Your nearness where I feel afraid.', NULL, 'prayer', 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.', 'Hebrews 4:16 KJV', 'approved'),
('God''s grace can find you even when you feel hard to find.', NULL, 'encouragement', 'My grace is sufficient for thee: for my strength is made perfect in weakness.', '2 Corinthians 12:9 KJV', 'approved'),
('The peace of Christ can visit your body, not only your thoughts.', NULL, 'encouragement', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.', 'John 14:27 KJV', 'approved'),
('You are not too late for mercy.', NULL, 'encouragement', 'It is of the LORD''s mercies that we are not consumed, because his compassions fail not.', 'Lamentations 3:22 KJV', 'approved'),
('God can teach your heart to exhale again.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('The Lord can hold the truth of what happened and the hope of what is coming.', NULL, 'encouragement', 'Now the God of hope fill you with all joy and peace in believing.', 'Romans 15:13 KJV', 'approved'),
('Healing with God can be quiet, honest, and unhurried.', NULL, 'encouragement', 'He healeth the broken in heart, and bindeth up their wounds.', 'Psalm 147:3 KJV', 'approved'),
('Your story can still carry light.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('God is faithful in the breath between now and next.', NULL, 'saying', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('You can ask God for help before you feel brave.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('The Lord can cover the places where shame has been loud.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('Mercy meets you before you get yourself together.', NULL, 'saying', 'It is of the LORD''s mercies that we are not consumed, because his compassions fail not.', 'Lamentations 3:22 KJV', 'approved'),
('You are not forgotten by heaven.', NULL, 'encouragement', 'I will never leave thee, nor forsake thee.', 'Hebrews 13:5 KJV', 'approved'),
('The Lord can turn a small step into holy ground.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('God can comfort the part of you that is still waiting to feel safe.', NULL, 'encouragement', 'Blessed are they that mourn: for they shall be comforted.', 'Matthew 5:4 KJV', 'approved'),
('Lord, remind me that I am not alone in this room.', NULL, 'prayer', 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.', 'Hebrews 4:16 KJV', 'approved'),
('Jesus is near enough for this moment.', NULL, 'encouragement', 'Draw nigh to God, and he will draw nigh to you.', 'James 4:8 KJV', 'approved'),
('God can make your home, your mind, and your body feel softer over time.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('The Lord''s kindness can reach behind the wall you built to survive.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('You can be honest, tired, and loved at the same time.', NULL, 'encouragement', 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.', 'Matthew 11:28 KJV', 'approved'),
('Grace can hold what you cannot explain.', NULL, 'saying', 'My grace is sufficient for thee: for my strength is made perfect in weakness.', '2 Corinthians 12:9 KJV', 'approved'),
('God''s peace may come quietly, but it is still real.', NULL, 'encouragement', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.', 'John 14:27 KJV', 'approved'),
('The Lord can lead you beside still waters again.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('You are allowed to receive comfort without guilt.', NULL, 'encouragement', 'Blessed are they that mourn: for they shall be comforted.', 'Matthew 5:4 KJV', 'approved'),
('Christ is not far from the bruised heart.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('Lord, give me courage without taking away my tenderness.', NULL, 'prayer', 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.', 'Hebrews 4:16 KJV', 'approved'),
('God can renew strength without demanding that you hide your weakness.', NULL, 'encouragement', 'God is our refuge and strength, a very present help in trouble.', 'Psalm 46:1 KJV', 'approved'),
('Your worth was never dependent on being unhurt.', NULL, 'encouragement', 'The LORD is nigh unto them that are of a broken heart.', 'Psalm 34:18 KJV', 'approved'),
('The Lord can turn fear into trust one tiny surrender at a time.', NULL, 'encouragement', 'Fear thou not; for I am with thee: be not dismayed; for I am thy God.', 'Isaiah 41:10 KJV', 'approved'),
('Even here, God is still good and still near.', NULL, 'encouragement', 'Draw nigh to God, and he will draw nigh to you.', 'James 4:8 KJV', 'approved'),
('You can let the Word of God speak gently over your nervous system.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('The same Jesus who calmed the sea can calm the storm inside you.', NULL, 'saying', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.', 'John 14:27 KJV', 'approved');
INSERT OR IGNORE INTO faith_messages (message, reference, kind, verse_text, verse_reference, status) VALUES
('God is not finished bringing peace to your story.', NULL, 'encouragement', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.', 'John 14:27 KJV', 'approved'),
('You are held by mercy deeper than your memories.', NULL, 'encouragement', 'It is of the LORD''s mercies that we are not consumed, because his compassions fail not.', 'Lamentations 3:22 KJV', 'approved'),
('Lord, help me believe that Your grace is for this version of me too.', NULL, 'prayer', 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.', 'Hebrews 4:16 KJV', 'approved'),
('God can give you peace for today without showing you every answer for tomorrow.', NULL, 'encouragement', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.', 'John 14:27 KJV', 'approved'),
('The Lord is close enough to hear the prayer you barely whispered.', NULL, 'encouragement', 'Draw nigh to God, and he will draw nigh to you.', 'James 4:8 KJV', 'approved'),
('You are not a burden to the One who invites the weary to come.', NULL, 'encouragement', 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.', 'Matthew 11:28 KJV', 'approved'),
('Faith can look like choosing one breath with God.', NULL, 'saying', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('The Lord can restore what was stolen slowly, beautifully, and faithfully.', NULL, 'encouragement', 'Return unto thy rest, O my soul; for the LORD hath dealt bountifully with thee.', 'Psalm 116:7 KJV', 'approved'),
('God can bring holy calm to ordinary moments.', NULL, 'encouragement', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.', 'John 14:27 KJV', 'approved'),
('The cross is proof that love entered suffering and did not run from it.', NULL, 'saying', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('You can let God be strong where you feel weak.', NULL, 'encouragement', 'God is our refuge and strength, a very present help in trouble.', 'Psalm 46:1 KJV', 'approved'),
('The Lord can meet you with mercy before anyone else understands.', NULL, 'encouragement', 'It is of the LORD''s mercies that we are not consumed, because his compassions fail not.', 'Lamentations 3:22 KJV', 'approved'),
('God can teach your heart that peace is not a trap.', NULL, 'encouragement', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.', 'John 14:27 KJV', 'approved'),
('Lord, help me surrender what I cannot solve tonight.', NULL, 'prayer', 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.', 'Hebrews 4:16 KJV', 'approved'),
('The love of Christ is stronger than the fear that tries to define you.', NULL, 'encouragement', 'Fear thou not; for I am with thee: be not dismayed; for I am thy God.', 'Isaiah 41:10 KJV', 'approved'),
('You can have questions and still be held by God.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('The Lord can redeem even the places that feel too painful to name.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('God''s grace is not thin. It is strong enough for today.', NULL, 'encouragement', 'God is our refuge and strength, a very present help in trouble.', 'Psalm 46:1 KJV', 'approved'),
('You are seen by God in the moment no one else notices.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('Jesus can bring rest to the part of you that keeps bracing.', NULL, 'encouragement', 'Return unto thy rest, O my soul; for the LORD hath dealt bountifully with thee.', 'Psalm 116:7 KJV', 'approved'),
('The Lord can walk slowly with you until safety feels possible again.', NULL, 'encouragement', 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.', 'John 14:27 KJV', 'approved'),
('You are loved without needing to prove you are okay.', NULL, 'encouragement', 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'Nahum 1:7 KJV', 'approved'),
('God can put peace back into places where fear has been living.', NULL, 'encouragement', 'Fear thou not; for I am with thee: be not dismayed; for I am thy God.', 'Isaiah 41:10 KJV', 'approved'),
('Lord, let Your peace guard my heart and mind today.', NULL, 'prayer', 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.', 'Hebrews 4:16 KJV', 'approved');
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'God is our refuge and strength, a very present help in trouble.'), verse_reference = COALESCE(verse_reference, 'Psalm 46:1 KJV') WHERE message = 'God is our refuge and strength, a very present help in trouble.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Fear thou not; for I am with thee: be not dismayed; for I am thy God.'), verse_reference = COALESCE(verse_reference, 'Isaiah 41:10 KJV') WHERE message = 'Fear thou not; for I am with thee: be not dismayed; for I am thy God.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.'), verse_reference = COALESCE(verse_reference, 'Matthew 11:28 KJV') WHERE message = 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Peace I leave with you, my peace I give unto you.'), verse_reference = COALESCE(verse_reference, 'John 14:27 KJV') WHERE message = 'Peace I leave with you, my peace I give unto you.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is nigh unto them that are of a broken heart.'), verse_reference = COALESCE(verse_reference, 'Psalm 34:18 KJV') WHERE message = 'The LORD is nigh unto them that are of a broken heart.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.'), verse_reference = COALESCE(verse_reference, '2 Timothy 1:7 KJV') WHERE message = 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Be strong and of a good courage; be not afraid, neither be thou dismayed.'), verse_reference = COALESCE(verse_reference, 'Joshua 1:9 KJV') WHERE message = 'Be strong and of a good courage; be not afraid, neither be thou dismayed.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is my shepherd; I shall not want.'), verse_reference = COALESCE(verse_reference, 'Psalm 23:1 KJV') WHERE message = 'The LORD is my shepherd; I shall not want.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Cast thy burden upon the LORD, and he shall sustain thee.'), verse_reference = COALESCE(verse_reference, 'Psalm 55:22 KJV') WHERE message = 'Cast thy burden upon the LORD, and he shall sustain thee.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'He healeth the broken in heart, and bindeth up their wounds.'), verse_reference = COALESCE(verse_reference, 'Psalm 147:3 KJV') WHERE message = 'He healeth the broken in heart, and bindeth up their wounds.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Thou wilt keep him in perfect peace, whose mind is stayed on thee.'), verse_reference = COALESCE(verse_reference, 'Isaiah 26:3 KJV') WHERE message = 'Thou wilt keep him in perfect peace, whose mind is stayed on thee.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'They that wait upon the LORD shall renew their strength.'), verse_reference = COALESCE(verse_reference, 'Isaiah 40:31 KJV') WHERE message = 'They that wait upon the LORD shall renew their strength.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'When thou passest through the waters, I will be with thee.'), verse_reference = COALESCE(verse_reference, 'Isaiah 43:2 KJV') WHERE message = 'When thou passest through the waters, I will be with thee.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'They are new every morning: great is thy faithfulness.'), verse_reference = COALESCE(verse_reference, 'Lamentations 3:23 KJV') WHERE message = 'They are new every morning: great is thy faithfulness.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Blessed are they that mourn: for they shall be comforted.'), verse_reference = COALESCE(verse_reference, 'Matthew 5:4 KJV') WHERE message = 'Blessed are they that mourn: for they shall be comforted.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Be not afraid, only believe.'), verse_reference = COALESCE(verse_reference, 'Mark 5:36 KJV') WHERE message = 'Be not afraid, only believe.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'If God be for us, who can be against us?'), verse_reference = COALESCE(verse_reference, 'Romans 8:31 KJV') WHERE message = 'If God be for us, who can be against us?';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'My grace is sufficient for thee: for my strength is made perfect in weakness.'), verse_reference = COALESCE(verse_reference, '2 Corinthians 12:9 KJV') WHERE message = 'My grace is sufficient for thee: for my strength is made perfect in weakness.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'I can do all things through Christ which strengtheneth me.'), verse_reference = COALESCE(verse_reference, 'Philippians 4:13 KJV') WHERE message = 'I can do all things through Christ which strengtheneth me.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'I will never leave thee, nor forsake thee.'), verse_reference = COALESCE(verse_reference, 'Hebrews 13:5 KJV') WHERE message = 'I will never leave thee, nor forsake thee.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Casting all your care upon him; for he careth for you.'), verse_reference = COALESCE(verse_reference, '1 Peter 5:7 KJV') WHERE message = 'Casting all your care upon him; for he careth for you.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'There is no fear in love; but perfect love casteth out fear.'), verse_reference = COALESCE(verse_reference, '1 John 4:18 KJV') WHERE message = 'There is no fear in love; but perfect love casteth out fear.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD will give strength unto his people; the LORD will bless his people with peace.'), verse_reference = COALESCE(verse_reference, 'Psalm 29:11 KJV') WHERE message = 'The LORD will give strength unto his people; the LORD will bless his people with peace.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Weeping may endure for a night, but joy cometh in the morning.'), verse_reference = COALESCE(verse_reference, 'Psalm 30:5 KJV') WHERE message = 'Weeping may endure for a night, but joy cometh in the morning.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Be of good courage, and he shall strengthen your heart.'), verse_reference = COALESCE(verse_reference, 'Psalm 31:24 KJV') WHERE message = 'Be of good courage, and he shall strengthen your heart.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'In the multitude of my thoughts within me thy comforts delight my soul.'), verse_reference = COALESCE(verse_reference, 'Psalm 94:19 KJV') WHERE message = 'In the multitude of my thoughts within me thy comforts delight my soul.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is on my side; I will not fear.'), verse_reference = COALESCE(verse_reference, 'Psalm 118:6 KJV') WHERE message = 'The LORD is on my side; I will not fear.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Trust in the LORD with all thine heart; and lean not unto thine own understanding.'), verse_reference = COALESCE(verse_reference, 'Proverbs 3:5 KJV') WHERE message = 'Trust in the LORD with all thine heart; and lean not unto thine own understanding.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The name of the LORD is a strong tower: the righteous runneth into it, and is safe.'), verse_reference = COALESCE(verse_reference, 'Proverbs 18:10 KJV') WHERE message = 'The name of the LORD is a strong tower: the righteous runneth into it, and is safe.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'For we walk by faith, not by sight.'), verse_reference = COALESCE(verse_reference, '2 Corinthians 5:7 KJV') WHERE message = 'For we walk by faith, not by sight.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Pray without ceasing.'), verse_reference = COALESCE(verse_reference, '1 Thessalonians 5:17 KJV') WHERE message = 'Pray without ceasing.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Jesus Christ the same yesterday, and to day, and for ever.'), verse_reference = COALESCE(verse_reference, 'Hebrews 13:8 KJV') WHERE message = 'Jesus Christ the same yesterday, and to day, and for ever.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'God can meet you in the middle of the breath you are barely able to take.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'God is our refuge and strength, a very present help in trouble.'), verse_reference = COALESCE(verse_reference, 'Psalm 46:1 KJV') WHERE message = 'You do not have to be strong enough for the whole road. Ask God for grace for the next step.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.'), verse_reference = COALESCE(verse_reference, 'Matthew 11:28 KJV') WHERE message = 'The Lord is not disappointed by your tiredness. He is gentle with the weary.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'He healeth the broken in heart, and bindeth up their wounds.'), verse_reference = COALESCE(verse_reference, 'Psalm 147:3 KJV') WHERE message = 'Healing can be slow and still be sacred.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'My grace is sufficient for thee: for my strength is made perfect in weakness.'), verse_reference = COALESCE(verse_reference, '2 Corinthians 12:9 KJV') WHERE message = 'Grace is not only for your polished places. Grace meets you in the places you hide.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is nigh unto them that are of a broken heart.'), verse_reference = COALESCE(verse_reference, 'Psalm 34:18 KJV') WHERE message = 'God is not asking you to pretend this does not hurt.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Casting all your care upon him; for he careth for you.'), verse_reference = COALESCE(verse_reference, '1 Peter 5:7 KJV') WHERE message = 'You can bring the anxious thought to Jesus before you know how to fix it.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'And God shall wipe away all tears from their eyes.'), verse_reference = COALESCE(verse_reference, 'Revelation 21:4 KJV') WHERE message = 'Your tears are not wasted in the presence of God.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself.'), verse_reference = COALESCE(verse_reference, 'Matthew 6:34 KJV') WHERE message = 'The same God who holds tomorrow can hold this minute.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is nigh unto them that are of a broken heart.'), verse_reference = COALESCE(verse_reference, 'Psalm 34:18 KJV') WHERE message = 'You are not too broken for the love of Christ.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.'), verse_reference = COALESCE(verse_reference, 'John 14:27 KJV') WHERE message = 'God can restore peace without rushing your process.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.'), verse_reference = COALESCE(verse_reference, 'Hebrews 4:16 KJV') WHERE message = 'A small prayer still reaches heaven.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.'), verse_reference = COALESCE(verse_reference, 'Hebrews 4:16 KJV') WHERE message = 'You can whisper, ''Lord, help me,'' and that is enough for this moment.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'God sees the part of you that kept going quietly.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Yea, though I walk through the valley of the shadow of death, I will fear no evil.'), verse_reference = COALESCE(verse_reference, 'Psalm 23:4 KJV') WHERE message = 'The valley is real, but so is the Shepherd.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'My grace is sufficient for thee: for my strength is made perfect in weakness.'), verse_reference = COALESCE(verse_reference, '2 Corinthians 12:9 KJV') WHERE message = 'You are held by a grace that does not let go when you feel weak.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Fear thou not; for I am with thee: be not dismayed; for I am thy God.'), verse_reference = COALESCE(verse_reference, 'Isaiah 41:10 KJV') WHERE message = 'God''s nearness is not canceled by your fear.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Return unto thy rest, O my soul; for the LORD hath dealt bountifully with thee.'), verse_reference = COALESCE(verse_reference, 'Psalm 116:7 KJV') WHERE message = 'You can rest without earning it. Rest was God''s idea first.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Blessed are they that mourn: for they shall be comforted.'), verse_reference = COALESCE(verse_reference, 'Matthew 5:4 KJV') WHERE message = 'Jesus is not offended by your need for comfort.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.'), verse_reference = COALESCE(verse_reference, 'John 14:27 KJV') WHERE message = 'The Lord can make room for peace even in a crowded heart.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'God is still writing tenderness into your story.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'He healeth the broken in heart, and bindeth up their wounds.'), verse_reference = COALESCE(verse_reference, 'Psalm 147:3 KJV') WHERE message = 'There is mercy for the version of you that is still learning how to heal.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'My grace is sufficient for thee: for my strength is made perfect in weakness.'), verse_reference = COALESCE(verse_reference, '2 Corinthians 12:9 KJV') WHERE message = 'You do not have to carry shame into a place where Jesus offers grace.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.'), verse_reference = COALESCE(verse_reference, 'John 14:27 KJV') WHERE message = 'Your nervous system may feel unsafe, but your soul can be reminded that God is near.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.'), verse_reference = COALESCE(verse_reference, 'Hebrews 4:16 KJV') WHERE message = 'Today, let prayer be simple: Lord, stay close.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'The Lord does not despise small beginnings or small steps.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'God''s love is not fragile. It can hold your questions.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is nigh unto them that are of a broken heart.'), verse_reference = COALESCE(verse_reference, 'Psalm 34:18 KJV') WHERE message = 'You can be honest with God about the part that still hurts.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'Faith does not mean you never tremble. Sometimes faith is reaching for God while you tremble.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.'), verse_reference = COALESCE(verse_reference, 'John 14:27 KJV') WHERE message = 'God can bring calm to places that have only known survival.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'I will never leave thee, nor forsake thee.'), verse_reference = COALESCE(verse_reference, 'Hebrews 13:5 KJV') WHERE message = 'You are not forgotten in the quiet season.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Blessed are they that mourn: for they shall be comforted.'), verse_reference = COALESCE(verse_reference, 'Matthew 5:4 KJV') WHERE message = 'The Holy Spirit can comfort what words cannot explain.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.'), verse_reference = COALESCE(verse_reference, 'Hebrews 4:16 KJV') WHERE message = 'Lord, give me enough peace for this moment and enough courage for the next one.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Now the God of hope fill you with all joy and peace in believing.'), verse_reference = COALESCE(verse_reference, 'Romans 15:13 KJV') WHERE message = 'God is not waiting for you to be less human before He loves you.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.'), verse_reference = COALESCE(verse_reference, 'Matthew 11:28 KJV') WHERE message = 'There is room at the feet of Jesus for your exhaustion.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'My grace is sufficient for thee: for my strength is made perfect in weakness.'), verse_reference = COALESCE(verse_reference, '2 Corinthians 12:9 KJV') WHERE message = 'Your weakness is not a locked door to God. It is often where grace enters.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'Even when your heart feels scattered, God can gather you gently.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'You can lay down what was never yours to carry.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'He healeth the broken in heart, and bindeth up their wounds.'), verse_reference = COALESCE(verse_reference, 'Psalm 147:3 KJV') WHERE message = 'The Lord is patient with slow healing.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.'), verse_reference = COALESCE(verse_reference, 'John 14:27 KJV') WHERE message = 'You do not have to perform peace to be loved by the Prince of Peace.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'A hard season does not mean God has turned away.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Trust in the LORD with all thine heart; and lean not unto thine own understanding.'), verse_reference = COALESCE(verse_reference, 'Proverbs 3:5 KJV') WHERE message = 'God can be trusted with the chapter you would not have chosen.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'My grace is sufficient for thee: for my strength is made perfect in weakness.'), verse_reference = COALESCE(verse_reference, '2 Corinthians 12:9 KJV') WHERE message = 'Let grace speak louder than the accusation in your mind.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'You are still seen, still loved, and still held.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.'), verse_reference = COALESCE(verse_reference, 'Hebrews 4:16 KJV') WHERE message = 'Lord, quiet what is racing and strengthen what is weary.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'Jesus meets people in storms, not only after storms.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'Your faith can be small and still be real.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Now the God of hope fill you with all joy and peace in believing.'), verse_reference = COALESCE(verse_reference, 'Romans 15:13 KJV') WHERE message = 'The Lord can hold both your hope and your heartbreak.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'It is of the LORD''s mercies that we are not consumed, because his compassions fail not.'), verse_reference = COALESCE(verse_reference, 'Lamentations 3:22 KJV') WHERE message = 'You can stop striving for a moment and receive mercy.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'God does not require perfect words. He receives honest prayers.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'This moment is not bigger than God''s compassion.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'The cross says your pain is not invisible to God.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'God can redeem what trauma tried to rename.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'He healeth the broken in heart, and bindeth up their wounds.'), verse_reference = COALESCE(verse_reference, 'Psalm 147:3 KJV') WHERE message = 'You are not beyond repair. The Restorer is gentle.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.'), verse_reference = COALESCE(verse_reference, 'John 14:27 KJV') WHERE message = 'The Lord can make your heart a safer place to live.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'When you cannot find the words, let your breathing become a prayer.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'He healeth the broken in heart, and bindeth up their wounds.'), verse_reference = COALESCE(verse_reference, 'Psalm 147:3 KJV') WHERE message = 'God is near in the ordinary, quiet, unimpressive steps of healing.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.'), verse_reference = COALESCE(verse_reference, 'Hebrews 4:16 KJV') WHERE message = 'Lord, help me receive the peace I cannot create by myself.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'My grace is sufficient for thee: for my strength is made perfect in weakness.'), verse_reference = COALESCE(verse_reference, '2 Corinthians 12:9 KJV') WHERE message = 'Grace is enough for the parts of you that feel unfinished.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'He healeth the broken in heart, and bindeth up their wounds.'), verse_reference = COALESCE(verse_reference, 'Psalm 147:3 KJV') WHERE message = 'You can trust God with the timing of your healing.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'There is no shame in needing God again today.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'God can bring light into rooms you thought would always stay dark.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Now the God of hope fill you with all joy and peace in believing.'), verse_reference = COALESCE(verse_reference, 'Romans 15:13 KJV') WHERE message = 'You are not alone in the waiting.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'The Lord''s gentleness can reach the memory that still aches.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'You can be loved by God before you feel whole.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'Faith is not denial. Faith is bringing the truth to the One who can hold it.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'It is of the LORD''s mercies that we are not consumed, because his compassions fail not.'), verse_reference = COALESCE(verse_reference, 'Lamentations 3:22 KJV') WHERE message = 'God''s mercy is not running out on you.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'You can ask for help and still be faithful.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'The Lord sees the battle nobody else noticed.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'He healeth the broken in heart, and bindeth up their wounds.'), verse_reference = COALESCE(verse_reference, 'Psalm 147:3 KJV') WHERE message = 'Jesus is not asking you to heal alone.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.'), verse_reference = COALESCE(verse_reference, 'John 14:27 KJV') WHERE message = 'God''s peace can be gentle before it feels strong.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.'), verse_reference = COALESCE(verse_reference, 'Hebrews 4:16 KJV') WHERE message = 'Lord, teach my body that Your presence is safe.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'Your story is not over because a chapter was painful.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'He healeth the broken in heart, and bindeth up their wounds.'), verse_reference = COALESCE(verse_reference, 'Psalm 147:3 KJV') WHERE message = 'The God who restores souls is not intimidated by your wounds.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Blessed are they that mourn: for they shall be comforted.'), verse_reference = COALESCE(verse_reference, 'Matthew 5:4 KJV') WHERE message = 'You are allowed to need comfort, prayer, and time.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'He healeth the broken in heart, and bindeth up their wounds.'), verse_reference = COALESCE(verse_reference, 'Psalm 147:3 KJV') WHERE message = 'God is not in a hurry with your healing.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'The Lord can turn survival into steadiness, one day at a time.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'You can bring God the mess, not just the lesson.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'He healeth the broken in heart, and bindeth up their wounds.'), verse_reference = COALESCE(verse_reference, 'Psalm 147:3 KJV') WHERE message = 'Jesus knows how to be gentle with wounded people.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'A quiet prayer can be an act of courage.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'God is our refuge and strength, a very present help in trouble.'), verse_reference = COALESCE(verse_reference, 'Psalm 46:1 KJV') WHERE message = 'God can strengthen you without hardening your heart.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Fear thou not; for I am with thee: be not dismayed; for I am thy God.'), verse_reference = COALESCE(verse_reference, 'Isaiah 41:10 KJV') WHERE message = 'Let the love of Christ be louder than the fear that says you are alone.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.'), verse_reference = COALESCE(verse_reference, 'John 14:27 KJV') WHERE message = 'The Lord can help you feel safe in small pieces.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'You do not have to understand everything to be held by God.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.'), verse_reference = COALESCE(verse_reference, 'John 14:27 KJV') WHERE message = 'God''s presence can be peace before your circumstances change.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.'), verse_reference = COALESCE(verse_reference, 'Hebrews 4:16 KJV') WHERE message = 'Lord, help me take the next right breath.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'You are not disqualified by the days you struggle.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Fear thou not; for I am with thee: be not dismayed; for I am thy God.'), verse_reference = COALESCE(verse_reference, 'Isaiah 41:10 KJV') WHERE message = 'Grace covers the places where survival taught you to be afraid.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Draw nigh to God, and he will draw nigh to you.'), verse_reference = COALESCE(verse_reference, 'James 4:8 KJV') WHERE message = 'God can be close even when your feelings are loud.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'You can be fragile and still be faithful.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is nigh unto them that are of a broken heart.'), verse_reference = COALESCE(verse_reference, 'Psalm 34:18 KJV') WHERE message = 'The Lord is not ashamed to be near your broken places.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'He healeth the broken in heart, and bindeth up their wounds.'), verse_reference = COALESCE(verse_reference, 'Psalm 147:3 KJV') WHERE message = 'Your healing matters to God.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Now the God of hope fill you with all joy and peace in believing.'), verse_reference = COALESCE(verse_reference, 'Romans 15:13 KJV') WHERE message = 'There is mercy for today and hope for tomorrow.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'I will never leave thee, nor forsake thee.'), verse_reference = COALESCE(verse_reference, 'Hebrews 13:5 KJV') WHERE message = 'Let Jesus be enough for the step you cannot take alone.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'God can carry what your hands cannot hold anymore.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'The Lord is still kind in the middle of the unknown.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Casting all your care upon him; for he careth for you.'), verse_reference = COALESCE(verse_reference, '1 Peter 5:7 KJV') WHERE message = 'You can rest beneath the care of a faithful Father.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'God''s love does not shrink back from hard stories.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'When your heart feels heavy, you can still be held.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.'), verse_reference = COALESCE(verse_reference, 'Hebrews 4:16 KJV') WHERE message = 'Lord, make a little room in me for peace today.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Yea, though I walk through the valley of the shadow of death, I will fear no evil.'), verse_reference = COALESCE(verse_reference, 'Psalm 23:4 KJV') WHERE message = 'The Shepherd does not abandon sheep in valleys.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'God can meet you in the pause before panic takes over.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'Your need is not too much for God''s compassion.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.'), verse_reference = COALESCE(verse_reference, 'John 14:27 KJV') WHERE message = 'The Lord can restore your sense of safety without forcing you to rush.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'Jesus can sit with you in the ache without demanding a performance.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'Your heart is worth tending gently.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'God can make beauty grow in soil that grief watered.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'I will never leave thee, nor forsake thee.'), verse_reference = COALESCE(verse_reference, 'Hebrews 13:5 KJV') WHERE message = 'You are not alone when the night feels long.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'The Lord understands groans that never become sentences.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'You can let prayer be small today.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'My grace is sufficient for thee: for my strength is made perfect in weakness.'), verse_reference = COALESCE(verse_reference, '2 Corinthians 12:9 KJV') WHERE message = 'Grace does not ask you to pretend you are fine.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Trust in the LORD with all thine heart; and lean not unto thine own understanding.'), verse_reference = COALESCE(verse_reference, 'Proverbs 3:5 KJV') WHERE message = 'God can rebuild trust slowly and tenderly.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'You are deeply loved in the middle of your process.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'The Lord can steady what trauma shook.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'And God shall wipe away all tears from their eyes.'), verse_reference = COALESCE(verse_reference, 'Revelation 21:4 KJV') WHERE message = 'God is not distant from your tears.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is nigh unto them that are of a broken heart.'), verse_reference = COALESCE(verse_reference, 'Psalm 34:18 KJV') WHERE message = 'You can bring the younger, hurting parts of you to Jesus.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.'), verse_reference = COALESCE(verse_reference, 'Hebrews 4:16 KJV') WHERE message = 'Lord, help me feel Your nearness where I feel afraid.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'My grace is sufficient for thee: for my strength is made perfect in weakness.'), verse_reference = COALESCE(verse_reference, '2 Corinthians 12:9 KJV') WHERE message = 'God''s grace can find you even when you feel hard to find.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.'), verse_reference = COALESCE(verse_reference, 'John 14:27 KJV') WHERE message = 'The peace of Christ can visit your body, not only your thoughts.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'It is of the LORD''s mercies that we are not consumed, because his compassions fail not.'), verse_reference = COALESCE(verse_reference, 'Lamentations 3:22 KJV') WHERE message = 'You are not too late for mercy.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'God can teach your heart to exhale again.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Now the God of hope fill you with all joy and peace in believing.'), verse_reference = COALESCE(verse_reference, 'Romans 15:13 KJV') WHERE message = 'The Lord can hold the truth of what happened and the hope of what is coming.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'He healeth the broken in heart, and bindeth up their wounds.'), verse_reference = COALESCE(verse_reference, 'Psalm 147:3 KJV') WHERE message = 'Healing with God can be quiet, honest, and unhurried.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'Your story can still carry light.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'God is faithful in the breath between now and next.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'You can ask God for help before you feel brave.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'The Lord can cover the places where shame has been loud.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'It is of the LORD''s mercies that we are not consumed, because his compassions fail not.'), verse_reference = COALESCE(verse_reference, 'Lamentations 3:22 KJV') WHERE message = 'Mercy meets you before you get yourself together.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'I will never leave thee, nor forsake thee.'), verse_reference = COALESCE(verse_reference, 'Hebrews 13:5 KJV') WHERE message = 'You are not forgotten by heaven.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'The Lord can turn a small step into holy ground.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Blessed are they that mourn: for they shall be comforted.'), verse_reference = COALESCE(verse_reference, 'Matthew 5:4 KJV') WHERE message = 'God can comfort the part of you that is still waiting to feel safe.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.'), verse_reference = COALESCE(verse_reference, 'Hebrews 4:16 KJV') WHERE message = 'Lord, remind me that I am not alone in this room.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Draw nigh to God, and he will draw nigh to you.'), verse_reference = COALESCE(verse_reference, 'James 4:8 KJV') WHERE message = 'Jesus is near enough for this moment.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'God can make your home, your mind, and your body feel softer over time.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'The Lord''s kindness can reach behind the wall you built to survive.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.'), verse_reference = COALESCE(verse_reference, 'Matthew 11:28 KJV') WHERE message = 'You can be honest, tired, and loved at the same time.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'My grace is sufficient for thee: for my strength is made perfect in weakness.'), verse_reference = COALESCE(verse_reference, '2 Corinthians 12:9 KJV') WHERE message = 'Grace can hold what you cannot explain.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.'), verse_reference = COALESCE(verse_reference, 'John 14:27 KJV') WHERE message = 'God''s peace may come quietly, but it is still real.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'The Lord can lead you beside still waters again.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Blessed are they that mourn: for they shall be comforted.'), verse_reference = COALESCE(verse_reference, 'Matthew 5:4 KJV') WHERE message = 'You are allowed to receive comfort without guilt.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'Christ is not far from the bruised heart.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.'), verse_reference = COALESCE(verse_reference, 'Hebrews 4:16 KJV') WHERE message = 'Lord, give me courage without taking away my tenderness.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'God is our refuge and strength, a very present help in trouble.'), verse_reference = COALESCE(verse_reference, 'Psalm 46:1 KJV') WHERE message = 'God can renew strength without demanding that you hide your weakness.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is nigh unto them that are of a broken heart.'), verse_reference = COALESCE(verse_reference, 'Psalm 34:18 KJV') WHERE message = 'Your worth was never dependent on being unhurt.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Fear thou not; for I am with thee: be not dismayed; for I am thy God.'), verse_reference = COALESCE(verse_reference, 'Isaiah 41:10 KJV') WHERE message = 'The Lord can turn fear into trust one tiny surrender at a time.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Draw nigh to God, and he will draw nigh to you.'), verse_reference = COALESCE(verse_reference, 'James 4:8 KJV') WHERE message = 'Even here, God is still good and still near.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'You can let the Word of God speak gently over your nervous system.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.'), verse_reference = COALESCE(verse_reference, 'John 14:27 KJV') WHERE message = 'The same Jesus who calmed the sea can calm the storm inside you.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.'), verse_reference = COALESCE(verse_reference, 'John 14:27 KJV') WHERE message = 'God is not finished bringing peace to your story.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'It is of the LORD''s mercies that we are not consumed, because his compassions fail not.'), verse_reference = COALESCE(verse_reference, 'Lamentations 3:22 KJV') WHERE message = 'You are held by mercy deeper than your memories.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.'), verse_reference = COALESCE(verse_reference, 'Hebrews 4:16 KJV') WHERE message = 'Lord, help me believe that Your grace is for this version of me too.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.'), verse_reference = COALESCE(verse_reference, 'John 14:27 KJV') WHERE message = 'God can give you peace for today without showing you every answer for tomorrow.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Draw nigh to God, and he will draw nigh to you.'), verse_reference = COALESCE(verse_reference, 'James 4:8 KJV') WHERE message = 'The Lord is close enough to hear the prayer you barely whispered.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.'), verse_reference = COALESCE(verse_reference, 'Matthew 11:28 KJV') WHERE message = 'You are not a burden to the One who invites the weary to come.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'Faith can look like choosing one breath with God.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Return unto thy rest, O my soul; for the LORD hath dealt bountifully with thee.'), verse_reference = COALESCE(verse_reference, 'Psalm 116:7 KJV') WHERE message = 'The Lord can restore what was stolen slowly, beautifully, and faithfully.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.'), verse_reference = COALESCE(verse_reference, 'John 14:27 KJV') WHERE message = 'God can bring holy calm to ordinary moments.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'The cross is proof that love entered suffering and did not run from it.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'God is our refuge and strength, a very present help in trouble.'), verse_reference = COALESCE(verse_reference, 'Psalm 46:1 KJV') WHERE message = 'You can let God be strong where you feel weak.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'It is of the LORD''s mercies that we are not consumed, because his compassions fail not.'), verse_reference = COALESCE(verse_reference, 'Lamentations 3:22 KJV') WHERE message = 'The Lord can meet you with mercy before anyone else understands.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.'), verse_reference = COALESCE(verse_reference, 'John 14:27 KJV') WHERE message = 'God can teach your heart that peace is not a trap.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.'), verse_reference = COALESCE(verse_reference, 'Hebrews 4:16 KJV') WHERE message = 'Lord, help me surrender what I cannot solve tonight.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Fear thou not; for I am with thee: be not dismayed; for I am thy God.'), verse_reference = COALESCE(verse_reference, 'Isaiah 41:10 KJV') WHERE message = 'The love of Christ is stronger than the fear that tries to define you.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'You can have questions and still be held by God.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'The Lord can redeem even the places that feel too painful to name.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'God is our refuge and strength, a very present help in trouble.'), verse_reference = COALESCE(verse_reference, 'Psalm 46:1 KJV') WHERE message = 'God''s grace is not thin. It is strong enough for today.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'You are seen by God in the moment no one else notices.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Return unto thy rest, O my soul; for the LORD hath dealt bountifully with thee.'), verse_reference = COALESCE(verse_reference, 'Psalm 116:7 KJV') WHERE message = 'Jesus can bring rest to the part of you that keeps bracing.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.'), verse_reference = COALESCE(verse_reference, 'John 14:27 KJV') WHERE message = 'The Lord can walk slowly with you until safety feels possible again.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.'), verse_reference = COALESCE(verse_reference, 'Nahum 1:7 KJV') WHERE message = 'You are loved without needing to prove you are okay.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Fear thou not; for I am with thee: be not dismayed; for I am thy God.'), verse_reference = COALESCE(verse_reference, 'Isaiah 41:10 KJV') WHERE message = 'God can put peace back into places where fear has been living.';
UPDATE faith_messages SET verse_text = COALESCE(verse_text, 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy.'), verse_reference = COALESCE(verse_reference, 'Hebrews 4:16 KJV') WHERE message = 'Lord, let Your peace guard my heart and mind today.';
