const fallbackMessages=[
"You are not alone in what you’re feeling.",
"You are allowed to take this day one breath at a time.",
"You do not have to earn rest. You are allowed to receive it.",
"There is still tenderness for you, even here.",
"You are more than what happened to you.",
"A hard day does not mean a hopeless life.",
"You can be healing and hurting at the same time.",
"Your story still has soft places ahead.",
"You are allowed to move slowly today.",
"What happened to you does not define all of you.",
"You do not have to explain your pain to deserve care.",
"You are allowed to need comfort.",
"You are not weak for feeling deeply.",
"Your nervous system is doing its best to protect you.",
"You can pause without falling behind.",
"You are worthy of peace, even before everything feels fixed.",
"Today does not have to be solved all at once.",
"You are allowed to take up space.",
"You are not a burden for needing support.",
"You can begin again as many times as you need.",
"Your feelings make sense, even when they are heavy.",
"You do not have to carry everything by yourself.",
"Rest is not quitting.",
"You are allowed to protect your peace.",
"There is no shame in needing a softer pace.",
"You are still here, and that matters.",
"Small steps still count.",
"You do not have to be okay to be loved.",
"You are allowed to feel proud of surviving.",
"Your healing does not have to look perfect.",
"You are not behind. You are becoming.",
"You can be gentle with the part of you that is tired.",
"You are allowed to outgrow old survival patterns.",
"You deserve relationships that feel safe.",
"You do not have to shrink to be accepted.",
"You are allowed to say no without explaining everything.",
"You can trust yourself one small choice at a time.",
"Your voice matters, even if it shakes.",
"You are not too much.",
"You are not hard to love.",
"You deserve kindness from yourself too.",
"You can let today be simple.",
"Your body deserves patience.",
"You are allowed to need more time.",
"You do not have to rush your healing.",
"You are allowed to be a work in progress.",
"You are not your worst moment.",
"You are allowed to choose peace over pressure.",
"You can grieve what hurt and still hope for what is ahead.",
"Your softness is not a weakness.",
"You are allowed to be cared for.",
"You do not have to make pain look pretty.",
"You are allowed to have boundaries.",
"Your boundary is not an apology.",
"You are allowed to walk away from what keeps hurting you.",
"You can honor your past without living there.",
"You deserve calm that does not feel temporary.",
"You are allowed to rest before you are exhausted.",
"You are allowed to ask for what you need.",
"You are learning safety again, and that takes time.",
"You are allowed to be honest about what hurts.",
"You can have a hard day and still be healing.",
"You are not failing because something triggered you.",
"You deserve patience on the messy days.",
"You do not have to punish yourself for being human.",
"You are allowed to celebrate tiny victories.",
"You are still worthy when you are tired.",
"You are allowed to receive love without earning it.",
"You are allowed to be seen.",
"You are not responsible for everyone’s comfort.",
"You can take your time coming back to yourself.",
"You are allowed to breathe before responding.",
"You can choose quiet without guilt.",
"You are not selfish for needing space.",
"You deserve a life that feels gentle to live in.",
"You are allowed to protect your heart.",
"You do not have to be strong every minute.",
"You are allowed to let someone safe help.",
"You can be proud of making it through today.",
"You are allowed to heal at your own pace.",
"You are allowed to change your mind.",
"You are allowed to leave survival mode slowly.",
"You deserve more than just getting through.",
"You are allowed to enjoy peace when it comes.",
"You are not broken beyond repair.",
"You are allowed to believe good things can still happen.",
"You can build a life that feels safer than the one you survived.",
"You are allowed to be new.",
"You are allowed to forgive yourself for how you coped.",
"You did what you had to do to get through.",
"You are allowed to need gentleness after being strong for so long.",
"You are allowed to stop proving your pain.",
"You are enough, even on the days you feel unfinished.",
"You deserve love that does not require performance.",
"You are allowed to be quiet and still matter.",
"You are allowed to be held by hope today.",
"You can take the next right breath.",
"You are allowed to be proud of staying.",
"You are allowed to protect your healing.",
"You are not alone in the slow parts.",
"You are allowed to be tender with your memories.",
"You can make room for joy without betraying your pain.",
"You are allowed to feel safe in your own life.",
"You are worthy of the same grace you give others.",
"You do not have to earn your place here.",
"You can be loved in the middle of the process.",
"You are allowed to be unfinished and still worthy.",
"You are allowed to find beauty again.",
"You are allowed to let your shoulders drop.",
"You are allowed to stop bracing for a moment.",
"You are doing better than your fear says you are.",
"You are allowed to believe your life can be softer.",
"You can take one small step and let that be enough.",
"You are allowed to rest your mind today.",
"You are allowed to be gentle with the younger version of you.",
"You are not alone in learning how to feel safe.",
"You deserve peace in your body and calm in your home.",
"You are allowed to release what was never yours to carry.",
"You are allowed to hope without having everything figured out.",
"You are still becoming, and that is a beautiful thing.",
"Your healing is allowed to be quiet.",
"You are allowed to start again tomorrow.",
"You are worthy of care on the days you cannot explain yourself.",
"You are allowed to choose softness today.",
"You are allowed to be safe without apologizing for it.",
"Your heart deserves a place to exhale.",
"You are allowed to stop carrying what belongs to yesterday.",
"You are not your triggers.",
"You are allowed to come home to yourself slowly.",
"You deserve peace that reaches your whole body.",
"You are allowed to let today be enough.",
"You are still worthy when you are overwhelmed.",
"You can be honest and still be loved.",
"You are allowed to move forward without forgetting.",
"You deserve a gentle place to land.",
"You are allowed to be proud of quiet progress.",
"You are allowed to need reassurance.",
"You do not have to make sense to everyone to be worthy.",
"You can be kind to yourself while you are learning.",
"You are allowed to be soft after surviving hard things.",
"You are allowed to stop measuring healing by productivity.",
"You are more resilient than the part of you that feels afraid.",
"You are allowed to protect the peace you fought for.",
"You can hold hope gently today.",
"You are not alone in the moments that feel invisible.",
"You deserve safety, steadiness, and kindness.",
"You are allowed to trust slow healing.",
"You can be grateful and still be grieving.",
"You are allowed to make space for yourself.",
"You deserve to be met with tenderness.",
"You are allowed to loosen your grip on survival.",
"You are still loved when you need quiet.",
"You can give yourself permission to rest.",
"You are allowed to be cared for without guilt.",
"You are allowed to stop rehearsing the worst outcome.",
"You are worthy of a peaceful beginning.",
"You are allowed to heal without proving anything.",
"You can take today in smaller pieces.",
"You are not alone, not today, not here.",
"You are allowed to believe that better is possible.",
"You deserve compassion from the person in the mirror.",
"You are allowed to lay down what is too heavy.",
"You are allowed to exist without performing strength."
];
function json(data,status=200){
return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
}
function fallbackMessage(){
return fallbackMessages[Math.floor(Math.random()*fallbackMessages.length)];
}
export async function onRequestGet({env}){
try{
if(!env.DB){return json({message:fallbackMessage(),source:"fallback"});}
const row=await env.DB.prepare("SELECT message FROM messages WHERE status = 'approved' ORDER BY RANDOM() LIMIT 1").first();
if(row&&row.message){return json({message:row.message,source:"database"});}
return json({message:fallbackMessage(),source:"fallback"});
}catch(error){
return json({message:fallbackMessage(),source:"fallback"});
}
}
